### ISSUE TITLE
The custom headers do not sended via xidel in POST request

### ISSUE THREAD

**Issue by Baltazar500** [benibela/xidel#117]
Hi.

xidel at POST - request (uploading an image) using the keys "-H" or "--header" does not send custom headers. Headers as Accept, Cookie, Accept-Language, Referer, X-Requested-With, etc are not sent. Used version - Xidel 0.9.9 (20250102.git996148081b6c93c22c33820eefc0f0b22f3a8d1c)

**Comment by benibela** [comment]
how do you make the request?

this works with my local build:

    xidel --method POST -H "Custom: ABC" -H "Accept: xxxxxxxxx" https://www.videlibri.de/cgi-bin/xidelecho.pl --download - | grep HTTP

**Comment by Baltazar500** [comment]
>how do you make the request?

Not downloading but uploading :)

```

xidel --proxy=192.168.1.22:1168 --no-check-certificate -se ".//*[@id='result']/tbody/tr[5]/td[2]/pre" -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Safari/537.36" -H 'referer: https://example.com' -F "f=@~/qrencode.png" 'https://zxing.org/w/decode'

```

![Image](https://github.com/user-attachments/assets/89873897-a296-417b-a0a3-9d29e1bcee1b)

The user agent via header "-H" is also ignored by the way. Only default set of headers

**Comment by benibela** [comment]
fixed: https://github.com/benibela/xidel/commit/f3134874d2e166c9163bbf7116f9f360efe9b158

It is --form not POST that is causing the issue

**Comment by Baltazar500** [comment]
@Reino17, 

>Btw, where's that screenshot from?

BURP Suite (intercepting proxy)

@benibela,

>It is --form not POST that is causing the issue

OK ... In the last night build, is this fixed? In build xidel 0.9.9 20250222.git3e7e88a6230719de8bb1c6d5cedaf615f5a86bdb, the problem is still :(

![Image](https://github.com/user-attachments/assets/97475c87-032c-46eb-99bc-bbdf090ebc5f)

**Comment by benibela** [comment]
>OK ... In the last night build, is this fixed?

it should be

**Comment by Baltazar500** [comment]
>it should be

After additional tests, this was confirmed. Headers are sent. Only a small problem remained. If the user-agent is set through the headers, and not through the switch,
 2 user-agent's is sended.


![Image](https://github.com/user-attachments/assets/8a042299-c1ee-4eb5-b7af-dbc1adf72dc8)
